export const messages = {
  en: {
    imageControlsHint:"Double-click to zoom fully or fit · Scroll to zoom · Drag to move", videoControlsHint:"F: fullscreen · Space: play / pause · ← / →: seek 5 seconds", fullscreenVideo:"Fullscreen video",
    soundsHint:"Explore sounds and atmospheres connected to this idea.", noSounds:"No closely related sounds found. Try a different subject.", soundsPartial:"Some sound searches could not be completed.", soundScene:"Sound scene", soundEvokes:"Evokes",
    artGallery:"The visual gallery", museumCollections:"Museum collections", artHint:"Explore artwork connected to this subject.", noArt:"No related artwork found. Try a different subject.", artPartial:"Some museum collections could not be reached.", visualConnections:"visual connections", clickToExplore:"Select an image to explore", expandImage:"Expand image", viewImage:"View image", unknownArtist:"Unknown artist", connectedThrough:"Connected through", visitMuseum:"Visit museum", imageUnavailable:"Image unavailable. Visit the museum to view the original.", closeImage:"Close image", imageCanvas:"Artwork viewer", previousImage:"Previous image", nextImage:"Next image", fitImage:"Fit image", zoomImage:"Zoom in",
    videoSetup:"Local video search needs setup. See the app’s setup guide or connect the optional YouTube source.",
    watchLearn:"Watch & learn", closeVideo:"Close video", openYouTube:"Open on YouTube", learningVideosHint:"Select a video to watch.", noLearningVideos:"No suitable educational videos found for this idea. Try a different subject.",
    discover:"Discover", favorites:"Favorites", history:"History", title:"Follow your curiosity.", intro:"Explore videos, sounds, art, and ideas through emojis.", discovery:"Discovery", savedIntro:"Your favorite ideas, ready to revisit.", historyIntro:"Pick up where you left off.", search:"Search a word, feeling, or emoji…", all:"All emojis", constellation:"Constellation", grid:"Grid", list:"List", matches:"emojis to explore", page:"Page", previous:"Previous page", next:"Next page", portalHint:"Drop an emoji here", open:"Open portal", select:"Choose an emoji", selected:"SELECTED EMOJI", pickHint:"Select one, then open the portal.", try:"TRY A SUBJECT", tips:["ocean","music","love","space"], empty:"No emojis in this orbit.", emptyHint:"Try ocean, music, love, or an emoji itself.", savedEmpty:"No favorites yet.", historyEmpty:"No discoveries yet.", clear:"Clear all", local:"Saved only on this device", reduced:"Reduce motion", locale:"Interface language", variants:"Choose a variant", loading:"Loading…", context:"A LITTLE CONTEXT", wiki:"Wikipedia excerpt", fallback:"English context", alternative:"Related subjects", change:"Change subject", subjectSearch:"Search a different subject", find:"Find", suggested:"Suggested subject", watch:"Watch", gifs:"GIFs", listen:"Listen", art:"Art", close:"Close gallery", retry:"Try again", noMedia:"No matching results from this source.", credentials:"This source isn’t connected yet.", quota:"This source has reached its limit or is temporarily unavailable.", timeout:"This source took a little too long.", network:"We couldn’t reach this source.", source:"Open source", revision:"Article revision", loadingSubject:"Finding the subject…", resolvingFallback:"Exploring the emoji’s standard meaning.", favorite:"Save discovery", unfavorite:"Remove favorite", play:"Play video", credit:"Creator", rights:"License", stop:"Closing stops playback.", association:"Related association", storage:"Your browser couldn’t save these changes. They’ll stay available for this visit.", saved:"Saved discoveries", recent:"Recent discoveries", minutes:"Just explored", powered:"Powered by", noSubjects:"No article matches found. Try another subject.", back:"Back to discovery", view:"Canvas view", count:"discoveries", wander:"Feeling curious?", surprise:"Surprise me", clearSearch:"Clear search", settings:"Preferences", connection:"Live sources · results may vary", subjectLabel:"Subject", broken:"Preview unavailable. Open the original source.", alternativeHint:"Choose a subject to change all sections.", results:"Subject results", maxFavorites:"Your 200 favorite slots are full. Remove one to save another.",
  },
  es: {
    imageControlsHint:"Doble clic para ampliar al máximo o ajustar · Rueda para ampliar · Arrastra para mover", videoControlsHint:"F: pantalla completa · Espacio: reproducir / pausar · ← / →: saltar 5 segundos", fullscreenVideo:"Video en pantalla completa",
    soundsHint:"Explora sonidos y ambientes relacionados con esta idea.", noSounds:"No encontramos sonidos suficientemente relacionados. Prueba otro tema.", soundsPartial:"No pudimos completar algunas búsquedas de sonidos.", soundScene:"Escena sonora", soundEvokes:"Evoca",
    artGallery:"La galería visual", museumCollections:"Colecciones de museos", artHint:"Explora obras de arte relacionadas con este tema.", noArt:"No encontramos obras relacionadas. Prueba otro tema.", artPartial:"No pudimos conectar con algunas colecciones de museos.", visualConnections:"conexiones visuales", clickToExplore:"Elige una imagen para explorar", expandImage:"Ampliar imagen", viewImage:"Ver imagen", unknownArtist:"Artista desconocido", connectedThrough:"Relacionado con", visitMuseum:"Visitar museo", imageUnavailable:"Imagen no disponible. Visita el museo para ver el original.", closeImage:"Cerrar imagen", imageCanvas:"Visor de obras de arte", previousImage:"Imagen anterior", nextImage:"Imagen siguiente", fitImage:"Ajustar imagen", zoomImage:"Ampliar",
    videoSetup:"La búsqueda local de videos necesita configuración. Consulta la guía de la app o conecta la fuente opcional de YouTube.",
    watchLearn:"Ver y aprender", closeVideo:"Cerrar video", openYouTube:"Abrir en YouTube", learningVideosHint:"Elige un video para verlo.", noLearningVideos:"No encontramos videos educativos adecuados para esta idea. Prueba otro tema.",
    discover:"Descubrir", favorites:"Favoritos", history:"Historial", title:"Sigue tu curiosidad.", intro:"Explora videos, sonidos, arte e ideas con emojis.", discovery:"Descubrimiento", savedIntro:"Tus ideas favoritas, listas para volver a explorar.", historyIntro:"Retoma tu exploración.", search:"Busca una palabra, emoción o emoji…", all:"Todos", constellation:"Constelación", grid:"Cuadrícula", list:"Lista", matches:"emojis para explorar", page:"Página", previous:"Página anterior", next:"Página siguiente", portalHint:"Arrastra un emoji aquí", open:"Abrir portal", select:"Elige un emoji", selected:"EMOJI SELECCIONADO", pickHint:"Selecciona uno y abre el portal.", try:"PRUEBA UN TEMA", tips:["océano","música","amor","espacio"], empty:"No hay emojis en esta órbita.", emptyHint:"Prueba océano, música, amor o un emoji.", savedEmpty:"Aún no hay favoritos.", historyEmpty:"Aún no hay descubrimientos.", clear:"Borrar todo", local:"Guardado solo en este dispositivo", reduced:"Reducir movimiento", locale:"Idioma de la interfaz", variants:"Elige una variante", loading:"Cargando…", context:"UN POCO DE CONTEXTO", wiki:"Extracto de Wikipedia", fallback:"Contexto en inglés", alternative:"Temas relacionados", change:"Cambiar tema", subjectSearch:"Busca un tema diferente", find:"Buscar", suggested:"Tema sugerido", watch:"Ver", gifs:"GIFs", listen:"Escuchar", art:"Arte", close:"Cerrar galería", retry:"Intentar de nuevo", noMedia:"No hay resultados relacionados en esta fuente.", credentials:"Esta fuente aún no está conectada.", quota:"Esta fuente alcanzó su límite o no está disponible.", timeout:"Esta fuente tardó demasiado.", network:"No pudimos conectar con esta fuente.", source:"Abrir fuente", revision:"Revisión del artículo", loadingSubject:"Buscando el tema…", resolvingFallback:"Explorando el significado habitual del emoji.", favorite:"Guardar descubrimiento", unfavorite:"Quitar favorito", play:"Reproducir video", credit:"Autor", rights:"Licencia", stop:"Al cerrar se detiene la reproducción.", association:"Asociación relacionada", storage:"Tu navegador no pudo guardar los cambios. Estarán disponibles durante esta visita.", saved:"Descubrimientos guardados", recent:"Descubrimientos recientes", minutes:"Explorado recientemente", powered:"Contenido de", noSubjects:"No encontramos artículos. Prueba otro tema.", back:"Volver a descubrir", view:"Vista del lienzo", count:"descubrimientos", wander:"¿Tienes curiosidad?", surprise:"Sorpréndeme", clearSearch:"Borrar búsqueda", settings:"Preferencias", connection:"Fuentes en vivo · los resultados pueden variar", subjectLabel:"Tema", broken:"Vista previa no disponible. Abre la fuente original.", alternativeHint:"Elige un tema para cambiar todas las secciones.", results:"Resultados de temas", maxFavorites:"Tus 200 favoritos están completos. Quita uno para guardar otro.",
  },
};
