import { describe, expect, it } from "vitest";
import { emojiById } from "@/lib/catalog";
import { createNode, emptyComposition, compileBrief, semanticIdentity } from "@/features/playground/model";
import { canvasIdentity, configurationIdentity, completeRestore, isStateSaved, makeState, projectState, parseState, restoreState, resultMatches, saveableState, stateIdentity, type CreationRecord } from "@/features/playground/creations";
import type { GenerationRun, GenerationSettings } from "@/features/generation/model";
const settings:GenerationSettings={kind:"poem",locale:"en",tone:"gentle",model:"test/text",reasoningEffort:"high"};
function board(){return {...emptyComposition(),nodes:[createNode(emojiById.get("2764")!,"en","a",0),createNode(emojiById.get("1F319")!,"en","b",1)]};}
function run(input=board()):GenerationRun{return {id:crypto.randomUUID(),createdAt:1,status:"succeeded",board:input,settings,brief:compileBrief(input,"en"),identity:semanticIdentity(input,"en"),result:{text:"A poem",model:"test/text",provider:"openrouter"}};}
const row=(state:ReturnType<typeof makeState>):CreationRecord=>({key:state.id,identity:stateIdentity(state),namespace:"local",collection:"saved",revision:1,state});
describe("creation tree identity",()=>{
  it("groups equivalent geometry regardless of generated node/edge IDs",()=>{const a=board();a.edges=[{id:"edge-a",source:"a",target:"b",label:"evokes"}];const b=structuredClone(a);b.nodes[0].id="other-a";b.nodes[1].id="other-b";b.edges=[{id:"other-edge",source:"other-a",target:"other-b",label:"evokes"}];expect(canvasIdentity(a)).toBe(canvasIdentity(b));expect(configurationIdentity(a,settings)).toBe(configurationIdentity(b,settings));});
  it("separates exact scene changes but puts interpretation changes in configuration branches",()=>{const original=board();for(const patch of [{x:20.01},{scale:2},{rotation:90},{glyph:"🌱"}]){const changed=structuredClone(original);Object.assign(changed.nodes[0],patch);expect(canvasIdentity(changed)).not.toBe(canvasIdentity(original));}expect(canvasIdentity({...original,nodes:[...original.nodes].reverse()})).not.toBe(canvasIdentity(original));const annotated=structuredClone(original);annotated.nodes[0].meaning="Anatomy";annotated.intent="A classroom";expect(canvasIdentity(annotated)).toBe(canvasIdentity(original));expect(configurationIdentity(annotated,settings)).not.toBe(configurationIdentity(original,settings));});
  it("keeps independent generations and edited output versions",()=>{const a=makeState(board(),settings,run()),b=makeState(a.board,settings,run());expect(stateIdentity(a)).not.toBe(stateIdentity(b));const edited=structuredClone(a);edited.run!.result!.text="Edited poem";expect(stateIdentity(edited)).not.toBe(stateIdentity(a));});
  it("marks exact saved states and their canvas/configuration projections",()=>{const state=makeState(board(),settings,run());const saved=[row(state)];expect(isStateSaved(state,saved)).toBe(true);expect(isStateSaved(projectState(state,"canvas","en"),saved)).toBe(true);const changed=structuredClone(state);changed.board.nodes[0].x++;expect(isStateSaved(changed,saved)).toBe(false);changed.board=structuredClone(state.board);expect(isStateSaved(changed,saved)).toBe(true);changed.run!.result!.text="Another version";expect(isStateSaved(changed,saved)).toBe(false);});
});
describe("restoration and provenance",()=>{
  it("restores a complete canvas-only state and clears prior configuration/result",()=>{const current=makeState(board(),settings,run());const source=makeState({...board(),nodes:[board().nodes[1]]},null);const restored=restoreState(current,source,completeRestore,"en").state;expect(restored.settings).toBeNull();expect(restored.run).toBeNull();expect(restored.board.nodes).toHaveLength(1);expect(restored.board.intent).toBe("");});
  it("applies only portable context to different geometry and retains target annotations",()=>{const currentBoard=board();currentBoard.nodes[0].meaning="Target meaning";currentBoard.nodes[0].customMeaning=true;const current=makeState(currentBoard,settings);const sourceBoard=board();sourceBoard.nodes[0].x++;sourceBoard.nodes[0].meaning="Source meaning";sourceBoard.intent="A different intent";const source=makeState(sourceBoard,{...settings,model:"another/model",locale:"es"});const restored=restoreState(current,source,{canvas:false,configuration:true,result:false},"en");expect(restored.partialContext).toBe(true);expect(restored.state.board.nodes[0].meaning).toBe("Target meaning");expect(restored.state.board.intent).toBe(sourceBoard.intent);expect(restored.state.settings?.locale).toBe("es");});
  it("rebinds matching emoji-specific context to the target's IDs",()=>{const target=board();target.nodes[0].id="target-a";target.nodes[1].id="target-b";const source=board();source.edges=[{id:"relation",source:"a",target:"b",label:"illuminates"}];source.nodes[0].note="A saved note";const restored=restoreState(makeState(target,settings),makeState(source,settings),{canvas:false,configuration:true,result:false},"en").state;expect(restored.board.edges[0]).toMatchObject({source:"target-a",target:"target-b"});expect(restored.board.nodes[0].note).toBe("A saved note");});
  it("allows result-only viewing without reparenting or saving a mismatched result",()=>{const generated=run();const target=board();target.nodes[0].x++;const current=makeState(target,settings);const source=makeState(generated.board,settings,generated);const restored=restoreState(current,source,{canvas:false,configuration:false,result:true},"en").state;expect(restored.board).toEqual(target);expect(restored.run?.board).toEqual(generated.board);expect(resultMatches(restored.board,restored.settings,restored.run)).toBe(false);expect(saveableState(restored).run).toBeNull();expect(saveableState(source).run).toEqual(generated);});
  it("handles all seven nonempty component selections without mutating source states",()=>{const source=makeState(board(),settings,run());const current=makeState({...board(),title:"Existing"},null);for(let mask=1;mask<8;mask++){const parts={canvas:!!(mask&1),configuration:!!(mask&2),result:!!(mask&4)};const restored=restoreState(current,source,parts,"en").state;expect(restored.run).toEqual(parts.result?source.run:current.run);expect(restored.settings).toEqual(parts.configuration?source.settings:current.settings);}expect(current.board.title).toBe("Existing");});
});

it("preserves valid authored inputs when optional stored output is damaged",()=>{const state=makeState(board(),settings,run());const broken={...state,run:{...state.run,settings:null}};expect(parseState(broken)).toMatchObject({board:state.board,settings,run:null});const invalidUsage=structuredClone(state);invalidUsage.run!.result!.usage={promptTokens:NaN,completionTokens:2};expect(parseState(invalidUsage).run?.result?.usage).toBeUndefined();});

it("canonicalizes persisted settings independently of object property order",()=>{const input=board();const reordered={model:settings.model,tone:settings.tone,reasoningEffort:settings.reasoningEffort,locale:settings.locale,kind:settings.kind};expect(configurationIdentity(input,reordered)).toBe(configurationIdentity(input,settings));const state=makeState(input,settings,run(input));expect(isStateSaved(state,[row(parseState(state))])).toBe(true);});

it("does not mark a blank inactive editor saved when an empty canvas has a saved configuration",()=>{expect(isStateSaved(makeState(emptyComposition(),null),[row(makeState(emptyComposition(),settings))])).toBe(false);});

it("retains long compiled briefs independently of the generated text limit",()=>{const state=makeState(board(),settings,run());state.run!.brief.interpretation="Long authored input. ".repeat(1000);expect(parseState(state).run?.brief.interpretation).toBe(state.run!.brief.interpretation);});
