"use client";
import { useEffect, useId, useMemo, useRef, useState } from "react";
import { Bookmark, BookmarkCheck, ChevronDown, FileText, FolderHeart, History, RotateCcw, Shapes, SlidersHorizontal, Trash2, X } from "lucide-react";
import type { Locale } from "@/lib/types";
import { creationTitle, type OutputKind } from "@/features/generation/model";
import { creationLabels } from "./creation-labels";
import { completeRestore, groupCreations, isStateSaved, projectState, type CreationRecord, type CreationState, type RestoreParts } from "./creations";
import { StoryContent } from "./StoryResults";
import EmojiArtwork from "./emoji-artwork";
import "./creations.css";

export function CanvasPreview({state,locale}:{state:CreationState;locale:Locale}) {
  const nodes=state.board.nodes;const left=Math.min(0,...nodes.map(n=>n.x)),right=Math.max(100,...nodes.map(n=>n.x)),top=Math.min(0,...nodes.map(n=>n.y)),bottom=Math.max(100,...nodes.map(n=>n.y));
  return <div className="cr-canvas-preview" role="img" aria-label={`${creationLabels[locale].canvas}: ${nodes.map(n=>n.label).join(", ")}`}>
    {nodes.map(n=><span key={n.id} style={{left:`${8+(n.x-left)/(right-left)*84}%`,top:`${12+(n.y-top)/(bottom-top)*76}%`,fontSize:`${Math.max(12,Math.min(64,30*n.scale))}px`,transform:`translate(-50%,-50%) rotate(${n.rotation}deg)`}}><EmojiArtwork glyph={n.glyph}/></span>)}
  </div>;
}
export function CreationDetail({state,locale,outputNames,onRestore,busy=false,onCopy}:{state:CreationState;locale:Locale;outputNames:Record<OutputKind,string>;onRestore:(state:CreationState,parts:RestoreParts)=>void;busy?:boolean;onCopy:(text:string)=>Promise<boolean>}) {
  const prefix=useId();const t=creationLabels[locale];const [part,setPart]=useState<"canvas"|"configuration"|"result">("canvas");const [parts,setParts]=useState<RestoreParts>(completeRestore);
  useEffect(()=>{setPart(state.run?"result":state.settings?"configuration":"canvas");setParts({canvas:true,configuration:!!state.settings,result:!!state.run});},[state]);
  return <div className="cr-detail">
    <div className="cr-component-tabs" role="tablist" aria-label={t.view}>{(["canvas","configuration","result"] as const).map(p=><button key={p} id={`${prefix}-tab-${p}`} role="tab" tabIndex={part===p?0:-1} aria-selected={part===p} aria-controls={`${prefix}-panel`} disabled={p==="configuration"?!state.settings:p==="result"?!state.run:false} onKeyDown={e=>{if(!["ArrowLeft","ArrowRight","Home","End"].includes(e.key))return;e.preventDefault();const tabs=[...e.currentTarget.parentElement!.querySelectorAll<HTMLButtonElement>("button:not([disabled])")];const i=tabs.indexOf(e.currentTarget),target=e.key==="Home"?tabs[0]:e.key==="End"?tabs.at(-1):tabs[(i+(e.key==="ArrowRight"?1:tabs.length-1))%tabs.length];target?.click();target?.focus();}} onClick={()=>setPart(p)}>{t[p]}</button>)}</div>
    <section id={`${prefix}-panel`} role="tabpanel" aria-labelledby={`${prefix}-tab-${part}`}>
      {part==="canvas"?<CanvasPreview state={state} locale={locale}/>:part==="configuration"&&state.settings?<div className="cr-context-detail"><dl><dt>{t.canvas}</dt><dd>{state.board.title||t.untitled}</dd><dt>{t.configuration}</dt><dd>{outputNames[state.settings.kind]} · {state.settings.model||"—"} · {state.settings.reasoningEffort||"default"}</dd></dl>{state.board.intent&&<p>{state.board.intent}</p>}{state.board.interpretation&&<blockquote>{state.board.interpretation}</blockquote>}<ul>{state.board.nodes.map(n=><li key={n.id}><span aria-hidden="true">{n.glyph}</span> {n.meaning}{n.note&&<small>{n.note}</small>}</li>)}</ul>{state.board.edges.map(e=><p key={e.id}>{state.board.nodes.find(n=>n.id===e.source)?.glyph} {e.label} → {state.board.nodes.find(n=>n.id===e.target)?.glyph}</p>)}</div>:state.run?<StoryContent run={state.run} locale={locale} outputName={outputNames[state.run.settings.kind]} stale={false} readOnly onEdit={()=>{}} onCopy={onCopy}/>:null}
    </section>
    <div className="cr-restore-actions"><button className="primary-button" disabled={busy} onClick={()=>onRestore(state,completeRestore)}><RotateCcw size={15}/>{t.restore}</button><details className="cr-partial-restore"><summary>{t.choose}<ChevronDown size={14}/></summary><div>{(["canvas","configuration","result"] as const).map(p=><label key={p}><input type="checkbox" checked={parts[p]} disabled={p==="configuration"?!state.settings:p==="result"?!state.run:false} onChange={e=>setParts(current=>({...current,[p]:e.target.checked}))}/>{t[p]}</label>)}<button className="pg-secondary" disabled={busy||!Object.values(parts).some(Boolean)} onClick={()=>onRestore(state,parts)}>{t.restoreSelected}</button></div></details></div>
  </div>;
}
export function SavedCreations({records,locale,outputNames,busy,onRestore,onRemove,onCopy,onBack}:{records:CreationRecord[];locale:Locale;outputNames:Record<OutputKind,string>;busy:boolean;onRestore:(state:CreationState,parts:RestoreParts)=>void;onRemove:(records:CreationRecord[])=>void;onCopy:(text:string)=>Promise<boolean>;onBack:()=>void}) {
  const t=creationLabels[locale],groups=groupCreations(records);const [selection,setSelection]=useState<{record:CreationRecord;depth:"canvas"|"configuration"|"result"}|null>(null);const [limit,setLimit]=useState(20);
  const selected=selection&&records.some(r=>r.key===selection.record.key)?selection:records[0]?{record:records[0],depth:"canvas" as const}:null;
  const state=useMemo(()=>selected?projectState(selected.record.state,selected.depth,locale):null,[selected?.record.state,selected?.depth,locale]);
  if(!groups.length)return <section className="cr-empty"><FolderHeart size={38} strokeWidth={1.3}/><h2>{t.emptySaved}</h2><p>{t.emptySavedHint}</p><button className="primary-button" onClick={onBack}>{t.back}</button></section>;
  // A stable projection avoids resetting the detail's selected component on unrelated renders.
  return <div className="cr-library"><nav className="cr-tree" aria-label={t.name}>{groups.slice(0,limit).map(group=>{
    const representative=group.records[group.records.length-1];const title=representative.state.board.title||t.untitled;
    const select=(record:CreationRecord,depth:"canvas"|"configuration"|"result")=>setSelection({record,depth});
    return <details key={group.key} open className="cr-tree-canvas"><summary><span aria-hidden="true">{group.board.nodes.slice(0,3).map(n=>n.glyph).join(" ")}</span><span>{title}</span></summary><button className="cr-tree-item" aria-pressed={selected?.record.key===representative.key&&selected.depth==="canvas"} onClick={()=>select(representative,"canvas")}><Shapes size={15}/>{t.canvas}</button>{[...group.configurations.entries()].filter(([key])=>key!=="null").map(([key,branch])=>{
      const row=branch[branch.length-1],settings=row.state.settings!;return <div className="cr-tree-branch" key={key}><button className="cr-tree-item" aria-pressed={selected?.record.key===row.key&&selected.depth==="configuration"} onClick={()=>select(row,"configuration")}><SlidersHorizontal size={14}/><span>{outputNames[settings.kind]}<small>{settings.model||"—"}</small></span></button><div className="cr-tree-results">{branch.filter(r=>r.state.run?.result).map(r=><button key={r.key} className="cr-tree-item" aria-pressed={selected?.record.key===r.key&&selected.depth==="result"} onClick={()=>select(r,"result")}><FileText size={14}/>{creationTitle(r.state.run!)||outputNames[r.state.run!.settings.kind]}</button>)}</div></div>;
    })}</details>;
  })}{groups.length>limit&&<button className="pg-secondary" onClick={()=>setLimit(n=>n+20)}>{t.showMore}</button>}</nav><section className="cr-library-detail">{state&&<><header><h2>{state.run?creationTitle(state.run)||t.result:state.board.title||t.untitled}</h2><span className="cr-saved"><BookmarkCheck size={14}/>{t.saved}</span></header><CreationDetail key={`${selected!.record.key}:${selected!.depth}`} state={state} locale={locale} outputNames={outputNames} busy={busy} onRestore={onRestore} onCopy={onCopy}/><button className="cr-remove-saved" onClick={()=>{
    const matches=selected!.depth==="canvas"?groups.find(g=>g.key===groupCreations([selected!.record])[0].key)!.records:selected!.depth==="configuration"?[...groupCreations(records).find(g=>g.key===groupCreations([selected!.record])[0].key)!.configurations.values()].find(branch=>branch.some(r=>r.key===selected!.record.key))!:[selected!.record];onRemove(matches);
  }}><Trash2 size={14}/>{t.remove}</button></>}</section></div>;
}
export function TemporaryCreations({records,saved,locale,outputNames,busy,onRestore,onSave,onRemove,onView,undo,onUndo}:{records:CreationRecord[];saved:CreationRecord[];locale:Locale;outputNames:Record<OutputKind,string>;busy:boolean;onRestore:(state:CreationState,parts:RestoreParts)=>void;onSave:(state:CreationState)=>void;onRemove:(records:CreationRecord[])=>void;onView:(state:CreationState)=>void;undo:boolean;onUndo:()=>void}) {
  const t=creationLabels[locale];const [selected,setSelected]=useState<string[]>([]),[limit,setLimit]=useState(15);const rows=records.slice(0,limit);const ids=selected.filter(id=>records.some(r=>r.key===id));
  return <section className="cr-temporary" aria-label={t.temporary}><header><div><h2><History size={18}/>{t.temporary}<span>{records.length}</span></h2><p>{t.temporaryHint}</p></div>{!!records.length&&<div className="cr-bulk-actions"><label><input type="checkbox" aria-label={t.selectAll} checked={ids.length===records.length} onChange={e=>setSelected(e.target.checked?records.map(r=>r.key):[])}/>{t.selectAll}</label><button disabled={!ids.length} onClick={()=>onRemove(records.filter(r=>ids.includes(r.key)))}><Trash2 size={14}/>{t.removeSelected}{ids.length?` (${ids.length})`:""}</button><button onClick={()=>onRemove(records)}>{t.removeAll}</button></div>}</header>
    {records.length?groupCreations(rows).map(group=><details key={group.key} className="cr-session-canvas" open><summary><span aria-hidden="true">{group.board.nodes.slice(0,3).map(n=>n.glyph).join(" ")}</span>{group.records[group.records.length-1].state.board.title||t.untitled}<ChevronDown size={14}/></summary>{[...group.configurations.entries()].map(([key,branch])=><div className="cr-session-branch" key={key}><h3>{branch[0].state.settings?`${outputNames[branch[0].state.settings.kind]} · ${branch[0].state.settings.model||"—"}`:t.canvasOnly}</h3>{branch.map(row=>{
      const state=row.state,run=state.run;return <article className="pg-history-card cr-checkpoint" key={row.key} data-state-id={state.id}><label className="cr-select"><input type="checkbox" aria-label={`${t.view}: ${run?creationTitle(run)||outputNames[run.settings.kind]:state.board.title||t.canvasOnly}`} checked={ids.includes(row.key)} onChange={e=>setSelected(current=>e.target.checked?[...current,row.key]:current.filter(id=>id!==row.key))}/></label><div className="cr-checkpoint-content"><button className="cr-open pg-history-read" onClick={()=>onView(state)}><span className="pg-history-title">{run?creationTitle(run)||outputNames[run.settings.kind]:state.board.title||t.canvasOnly}</span><span className="pg-history-excerpt">{run?.result?.text|| (run?.status==="running"?t.running:run?.status==="canceled"?t.cancelledShort:run?t.failed:state.board.intent||(state.settings?t.configurationOnly:t.canvasOnly))}</span></button><div className="cr-checkpoint-meta"><time dateTime={new Date(state.createdAt).toISOString()}>{new Date(state.createdAt).toLocaleString(locale,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</time>{isStateSaved(state,saved)&&<span className="cr-saved"><BookmarkCheck size={13}/>{t.saved}</span>}</div></div><div className="cr-checkpoint-actions"><button disabled={busy} onClick={()=>onRestore(state,completeRestore)}><RotateCcw size={14}/>{t.restore}</button><button onClick={()=>onSave(state)}><Bookmark size={14}/>{t.save}</button><button className="pg-history-delete" aria-label={`${t.remove}: ${run?creationTitle(run)||outputNames[run.settings.kind]:state.board.title||t.canvasOnly}`} onClick={()=>onRemove([row])}><Trash2 size={15}/></button></div></article>;
    })}</div>)}</details>):<p className="cr-empty-history">{t.emptyTemporary}</p>}
    {records.length>limit&&<button className="pg-secondary cr-more" onClick={()=>setLimit(n=>n+15)}>{t.showMore} ({records.length-limit})</button>}{undo&&<div className="storage-notice" role="status"><span>{t.removed}</span><button onClick={onUndo}>{t.undo}</button></div>}
  </section>;
}
export function CreationDialog({title,children,onCancel,locale}:{title:string;children:React.ReactNode;onCancel:()=>void;locale:Locale}) {
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const dialog=ref.current!;const previous=document.activeElement as HTMLElement|null;dialog.showModal();return()=>{dialog.close();previous?.focus({preventScroll:true});};},[]);
  return <dialog ref={ref} className="cr-dialog" aria-label={title} onCancel={e=>{e.preventDefault();onCancel();}}><header><h2>{title}</h2><button aria-label={creationLabels[locale].cancel} onClick={onCancel}><X size={18}/></button></header>{children}</dialog>;
}
