"use client";
import { useMemo, useState } from "react";
import { searchCatalog } from "@/lib/catalog";
import type { Locale } from "@/lib/types";
import type { AccountIdentity } from "./model";
import "./account.css";
export default function AuthScreen({account}:{account?:AccountIdentity}){
  const [locale,setLocale]=useState<Locale>("en"),[register,setRegister]=useState(false),[username,setUsername]=useState(""),[name,setName]=useState(""),[password,setPassword]=useState(""),[phrase,setPhrase]=useState(""),[query,setQuery]=useState(""),[emojiId,setEmojiId]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const es=locale==="es",emojis=useMemo(()=>searchCatalog(query,null).slice(0,72),[query]);
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");try{
    const path=account?"/api/account/activate":register?"/api/account/register":"/api/auth/sign-in/username";
    const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(account?{phrase,emojiId}:register?{username,name,password}:{username,password})});
    const body=await response.json();if(!response.ok){setError(response.status===429?"limit":account?"invitation":register&&/USERNAME.*(TAKEN|EXIST)|USER_ALREADY_EXISTS/.test(body.code||"")?"taken":register?"registration":"login");return;}
    setPassword("");setPhrase("");window.location.assign(account?"/":register?"/waiting-room":"/");
  }catch{setError("connection");}finally{setBusy(false);}}
  const errors=es?{limit:"Demasiados intentos. Espera un minuto.",invitation:"La frase y el emoji no coinciden con la invitación.",taken:"Este nombre de usuario ya está en uso.",registration:"No se pudo crear la cuenta. Revisa los campos.",login:"El usuario o la contraseña son incorrectos.",connection:"No se pudo conectar. Vuelve a intentarlo."}:{limit:"Too many attempts. Wait a minute.",invitation:"The phrase and emoji do not match the invitation.",taken:"That username is already taken.",registration:"The account could not be created. Check the fields.",login:"The username or password is incorrect.",connection:"Could not connect. Try again."};
  return <main className={`account-screen ${account?"account-waiting":""}`} lang={locale}><header><span className="account-brand">✧ Dream Maker</span><label>{es?"Idioma":"Language"}<select aria-label={es?"Idioma de la interfaz":"Interface language"} value={locale} onChange={e=>setLocale(e.target.value as Locale)}><option value="en">English</option><option value="es">Español</option></select></label></header><section className="account-card"><p className="account-kicker">{es?"Un espacio para explorar":"A space to explore"}</p><h1>{account?(es?"Tu invitación":"Your invitation"):register?(es?"Crea tu cuenta":"Create your account"):(es?"Bienvenido de nuevo":"Welcome back")}</h1><p>{account?(es?`Hola, ${account.name}. Introduce la frase y elige el emoji de tu invitación para entrar.`:`Hi, ${account.name}. Enter the phrase and choose the emoji from your invitation to enter.`):es?"Tus exploraciones y creaciones, en un solo lugar.":"Your explorations and creations, in one place."}</p>
    <form onSubmit={submit}>
      {account?<><label>{es?"Frase de invitación":"Invitation phrase"}<input required autoComplete="off" value={phrase} maxLength={500} onChange={e=>setPhrase(e.target.value)}/></label><fieldset><legend>{es?"Emoji de invitación":"Invitation emoji"}</legend><label>{es?"Buscar emojis":"Search emojis"}<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={es?"Por ejemplo: corazón":"For example: heart"}/></label><div className="account-emoji-picker">{emojis.map(emoji=><button key={emoji.id} type="button" aria-label={emoji.labels[locale]} aria-pressed={emojiId===emoji.id} onClick={()=>setEmojiId(emoji.id)}>{emoji.glyph}</button>)}</div>{emojiId&&<p>{es?"Emoji elegido":"Selected emoji"}: {searchCatalog("",null).find(e=>e.id===emojiId)?.glyph}</p>}</fieldset></>:<><label>{es?"Nombre de usuario":"Username"}<input required minLength={3} maxLength={30} pattern="[a-zA-Z0-9_.]{3,30}" autoComplete="username" autoCapitalize="none" spellCheck={false} value={username} onChange={e=>setUsername(e.target.value)}/></label>{register&&<label>{es?"Nombre visible":"Display name"}<input required maxLength={80} autoComplete="nickname" value={name} onChange={e=>setName(e.target.value)}/></label>}<label>{es?"Contraseña":"Password"}<input required type="password" minLength={register?12:undefined} maxLength={128} autoComplete={register?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)}/></label>{register&&<p className="account-hint">{es?"Usa entre 12 y 128 caracteres. Esta prueba de concepto no ofrece recuperación de contraseña.":"Use 12–128 characters. This proof of concept does not offer password recovery."}</p>}</>}
      {error&&<p role="alert" className="account-error">{errors[error as keyof typeof errors]}</p>}
      <button className="account-primary" disabled={busy||!!account&&!emojiId}>{busy?(es?"Un momento…":"One moment…"):account?(es?"Entrar":"Enter"):register?(es?"Crear cuenta":"Create account"):(es?"Iniciar sesión":"Sign in")}</button>
    </form>
    {account?<button className="account-switch" disabled={busy} onClick={async()=>{const response=await fetch("/api/auth/sign-out",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});if(response.ok)window.location.assign("/login");else setError("connection");}}>{es?"Cerrar sesión":"Sign out"}</button>:<button className="account-switch" disabled={busy} onClick={()=>{setRegister(!register);setError("");setPassword("");}}>{register?(es?"Ya tengo una cuenta":"I already have an account"):(es?"Crear una cuenta":"Create an account")}</button>}
  </section></main>;
}
